### ISSUE TITLE
Error: "Cannot read properties of undefined (reading 'data')"

### ISSUE THREAD

**Issue by EbonyLouis** [TBD54566975/web5-js#146]
## Community Member reported running into this issue: 

`Cannot read properties of undefined (reading 'data')
    at file:///Users/moises/Projects/depfin/src/dwn-service/node_modules/@tbd54566975/web5/dist/esm/main.mjs:238:15
    at async file:///Users/moises/Projects/depfin/src/dwn-service/src/server.js:69:20`

## Code that is producing the error:

```
const { records } = await web5.dwn.records.query({
      from: remoteDid,
      message: {
          filter: {
              schema: schema,
              dataFormat: dataFormat
          }
      }
    });
    const items = [];
```

    for (const record of records) {

      const text = await record.data.text();

      items.push({
        recordId : record.id,
        content : text
      });
    }
 

## Extra information: 
"The calling DID does have read privileges to the data" 

Here is [the thread in Discord](https://discord.com/channels/937858703112155166/1115717253992816692/1125594242694258839) to follow up

**Comment by moisesja** [comment]
It is an interesting situation. To stage the error, I had to serialize a numpy array in Python which holds image contents. Once I push that image to a DWN (via an API proxy to the DWN), the data saved fine. I was able to read the contents fine from the owner of the DWN's calls. The exception occurs when query comes from a remote DID, which curiously enough, is the same DID that pushed the data to the DWN.

**Comment by moisesja** [comment]
*The exception occurs when the query...

**Comment by michaelneale** [comment]
Protocol: 

`{
    "protocol": "https://datashield.me/medicalimages",
    "types": {
      "image": {
        "schema": "https://datashield.me/image",
        "dataFormats": ["text/plain"]
      },
      "imageMetadata": {
        "schema": "https://datashield.me/imageMetadata",
        "dataFormats": ["application/json"]
      },
      "originalImage": {
        "schema": "https://datashield.me/originalimage",
        "dataFormats": ["image/png"]
      }
    },
    "structure": {
      "image": {
        "$actions": [
            {
              "who": "anyone",
              "can": "write"
            },
            {
              "who": "author",
              "of": "image",
              "can": "read"
            },
            {
              "who": "recipient",
              "of": "image",
              "can": "read"
            }
        ]
      },
      "imageMetadata": {
        "$actions": [
            {
              "who": "anyone",
              "can": "write"
            },
            {
              "who": "author",
              "of": "imageMetadata",
              "can": "read"
            },
            {
              "who": "recipient",
              "of": "imageMetadata",
              "can": "read"
            }
        ]
      },
      "originalImage": {
        "$actions": [
            {
              "who": "anyone",
              "can": "write"
            },
            {
              "who": "author",
              "of": "originalImage",
              "can": "read"
            },
            {
              "who": "recipient",
              "of": "originalImage",
              "can": "read"
            }
        ]
      } 
    }
  }`

**Comment by michaelneale** [comment]
@moisesja I think what the issue is the protocol needs to be specified when it is written. I can't remember the rules around accessing remotely when there is no protocol even from same did (normally you don't directly read from remote did but it would sync the data over, and you read it locally).

**Comment by frankhinek** [comment]
Unable to reproduce.  The issue reported is also covered by existing test cases.
