### ISSUE TITLE
recordId should be a property of Filter

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/web5-js#154]
When querying by `recordID`, it's unnecessary to force the developer to also specify filter criteria since there's only one record that can match a record id.

```js
const {records} = await web5.dwn.records.query({
  message: {
    recordID: 'bafyreiaz5oycqbrnmmpvffxqyoqxvx6bcnqueprmt2qnvzcurpc52r5uyy',
    filter: {
      dataFormat: 'text/plain',
    }
  }
});
```

My suggestion is to make `filter` optional and only require it if `recordID` is not supplied.

This is not a major issue but it is a weird developer experience to force me to provide extra criteria when it's not actually needed to find the record by ID.

<hr/>

Update: my new request is to move `recordId` to the `filter` object to adhere to the DIF spec

> I checked the [DIF spec ](https://identity.foundation/decentralized-web-node/spec/#recordsquery)to make sure we're still adhering to it, and it does say that the object _may_ contain `filter` (not must). But it also shows `recordId` as one of the properties of `filter`. So, I think the fix here is just to move `recordId` to the `filter` object.
> 
> ![image](https://user-images.githubusercontent.com/15972783/253831823-8ea16613-419e-49f7-ad8e-4a900881b838.png)

**Comment by Developerayo** [comment]
Love the idea! @angiejones 
And it does ease development processes, 

Developers will no longer need to specify the `filter` object if a `recordID` was specified, and if a `recordID` is provided the `filter` object should equally be optional, and if none we just throw and error. 

Want me to push a PR for this? @angiejones @frankhinek or there's an internal idea around this.

**Comment by angiejones** [comment]
> Love the idea! @angiejones And it does ease development processes,
> 
> Developers will no longer need to specify the `filter` object if a `recordID` was specified, and if a `recordID` is provided the `filter` object should equally be optional, and if none we just throw and error.
> 
> Want me to push a PR for this? @angiejones @frankhinek or there's an internal idea around this.

sure, go for it! thanks Ayo! 🙏🏾

**Comment by angiejones** [comment]
I checked the [DIF spec ](https://identity.foundation/decentralized-web-node/spec/#recordsquery)to make sure we're still adhering to it, and it does say that the object *may* contain `filter` (not must). But it also shows `recordId` as one of the properties of `filter`. So, I think the fix here is just to move `recordId` to the `filter` object.

![image](https://github.com/TBD54566975/web5-js/assets/15972783/8ea16613-419e-49f7-ad8e-4a900881b838)

**Comment by Developerayo** [comment]
> I checked the [DIF spec ](https://identity.foundation/decentralized-web-node/spec/#recordsquery)to make sure we're still adhering to it, and it does say that the object _may_ contain `filter` (not must). But it also shows `recordId` as one of the properties of `filter`. So, I think the fix here is just to move `recordId` to the `filter` object.
> 
> ![image](https://user-images.githubusercontent.com/15972783/253831823-8ea16613-419e-49f7-ad8e-4a900881b838.png)

Ah! I see,
This is a good one as well.

**Comment by angiejones** [comment]
> > I checked the [DIF spec ](https://identity.foundation/decentralized-web-node/spec/#recordsquery)to make sure we're still adhering to it, and it does say that the object _may_ contain `filter` (not must). But it also shows `recordId` as one of the properties of `filter`. So, I think the fix here is just to move `recordId` to the `filter` object.
> > ![image](https://user-images.githubusercontent.com/15972783/253831823-8ea16613-419e-49f7-ad8e-4a900881b838.png)
> 
> Ah! I see, This is a good one as well, will fix.
> 
> ```js
> const {records} = await web5.dwn.records.query({
>   message: {
>     filter: {
>       dataFormat: 'text/plain',
>       recordID: 'bafyreiaz5oycqbrnmmpvffxqyoqxvx6bcnqueprmt2qnvzcurpc52r5uyy',
>     }
>   }
> });
> ```

yeah but then `recordId` should be all that's needed in filter

```js
const {records} = await web5.dwn.records.query({
  message: {
    filter: {
      recordId: 'bafyreiaz5oycqbrnmmpvffxqyoqxvx6bcnqueprmt2qnvzcurpc52r5uyy',
    }
  }
});
```

**Comment by frankhinek** [comment]
@angiejones and @Developerayo:

This is already possible with the Web5 SDK today so no change is required:

```typescript
const {records} = await web5.dwn.records.query({
  message: {
    filter: {
      recordId: 'bafyreiaz5oycqbrnmmpvffxqyoqxvx6bcnqueprmt2qnvzcurpc52r5uyy',
    }
  }
});
```

The type for the filter object is defined in the DWN SDK [here](https://github.com/TBD54566975/dwn-sdk-js/blob/6b00a09b54a138a464a228e1bde6a1ff7f0e9a58/src/types/records-types.ts#L80C1-L91C3) and all filtering properties are already optional:

```typescript
export type RecordsQueryFilter = {
  attester?: string;
  recipient?: string;
  protocol?: string;
  protocolPath?: string;
  contextId?: string;
  schema?: string;
  recordId?: string;
  parentId?: string;
  dataFormat?: string;
  dateCreated?: RangeCriterion;
};
```

The utility of a query is typically to provide a set of attributes as a filter and return a list of zero or more matching records.  In the case where the exact ID of the record is known, you are usually better off using `web5.dwn.records.read()`:

```typescript
web5.dwn.records.read({
  message: {
    recordId: 'bafyreiaz5oycqbrnmmpvffxqyoqxvx6bcnqueprmt2qnvzcurpc52r5uyy'
  }
});
```

The benefit is that you can return a specific record and its data, unlike a `RecordsQuery`, which as defined in DWN SDK, only returns the data payload if the record is less than 10KB.  This is done intentionally to avoid producing an unexpected large data transfer (e.g., one of the matching records has a 1GB data payload OR there are 1,000 matches that each contain a 1MB data payload).

**Comment by frankhinek** [comment]
One suggestion is that the docs for querying be expanded to include information about all of the possible records query filters:

https://developer.tbd.website/docs/web5/build/decentralized-web-nodes/query-from-dwn

**Comment by frankhinek** [comment]
> ok @frankhinek. I still think the `recordID` property on `message` is weird because `filter` is also required. How do you feel about just removing `message.recordID` especially since there's a `filter.recordId`?
> 
> ```js
> const {records} = await web5.dwn.records.query({
>   message: {
>     recordID: 'bafyreiaz5oycqbrnmmpvffxqyoqxvx6bcnqueprmt2qnvzcurpc52r5uyy',
>     filter: {
>       dataFormat: 'text/plain',
>     }
>   }
> });
> ```
> 
> In the meantime, I'll just remove any examples in docs that use `message.recordID` and will use `filter.recordId` 👍🏾

`recordId` has never been a property of `message` with `web5.dwn.records.query()` -- it was always nested under `filter`

Since that time, `filter` is now being used with `web5.dwn.records.read()` and the docs have been updated to reflect the change:
https://github.com/TBD54566975/web5-js/blob/main/packages/api/README.md#web5dwnrecordsreadrequest
