### ISSUE TITLE
allow for custom DWN override in web5 connect. 

### ISSUE THREAD

**Issue by andorsk** [TBD54566975/web5-js#162]
is there a reason: 
https://github.com/TBD54566975/web5-js/blob/main/packages/web5/src/web5.ts#L72C1-L72C1 is private? 

I'm trying to implement something similar to :
https://github.com/TBD54566975/web5-js/blob/d8e2be7380e1ad504e7467d990dd942cead04ee5/packages/old/examples/simple-agent/src/utils.js#L20 

but because the constructor is private I am unable to: 
```sh
est/utils.ts:30:17 - error TS2673: Constructor of class 'Web5' is private and only accessible within the class declaration.

30   new Web5({ dwn: { node: dwnNode } });
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The context for this: I want to do some testing for interactions between two different DWNs in my test suite. If there's a better way to do this let me know!

**Comment by andorsk** [comment]
Want to clarify here that maybe another way to do this is override the `connect` api:

https://github.com/TBD54566975/web5-js/blob/d8e2be7380e1ad504e7467d990dd942cead04ee5/packages/web5/src/web5.ts#L112 

Note the above:

**Comment by andorsk** [comment]
Note PR: https://github.com/TBD54566975/web5-js/pull/163/files

**Comment by cbruguera** [comment]
Hey @andorsk Has there been any progress on this? I still cannot find a way to connect the web5 client to my locally running DWN, or even to use a specific DID to connect to the default DWNs. I don't know if I'm missing something... If there's a way to circumvent this limitation I'd appreciate any pointers.. 🙏

**Comment by andorsk** [comment]
@andorsk there's a few different things you are discussing in the above comment:

1. Sync (i.e connecting a remote DWN to a local one ) :  https://developer.tbd.website/docs/web5/learn/sync.
2. Adding a specific DID to a dWN, ( which this PR does slightly address  but not in completeness). https://github.com/TBD54566975/web5-js/blob/main/packages/web5/src/web5.ts#L127

There is supposed to be an update to web5 connect in the near future, so this PR is on hold until that PR gets merged. Tagging @frankhinek, who might know a little more about the web5 connect update here

**Comment by cbruguera** [comment]
@andorsk thanks for your reply. I'll look forward to that PR merge then.

In the meantime, however, what would be the way to connect to a local DWN?... Maybe I'm digressing a bit from the topic of this thread, but I'm running a DWN (from the dwn-server repo) and I would like to connect to it to do some simple data store and retrieve tests. Now, given that the web5 agent is not ready yet, what would be the way? Are there any other clients other than the web5 SDK, or should I connect to it through a third party JSON-RPC client? Is there any simple way to test the DWN server at the moment?

**Comment by andorsk** [comment]
@frankhinek awesome on the merge getting resolved today. That will be very helpful. Looking forward to it.

**Comment by andorsk** [comment]
@frankhinek took a look at that PR. 401 files is crazy. 🤯

**Comment by cbruguera** [comment]
@frankhinek yes, when I say "local" DWN I mean a dwn-server I'm manually running on my computer (either with docker or npm run server), so it would actually be a "remote" for the Web5 SDK, not the node running in memory. My question was how to connect to this node as I understood the SDK was only connecting to the default DWN URL endpoints and there was no overriding of it, but maybe I'm missing something.

I'm already making some related questions in the dwn channel on Discord. @frankhinek @andorsk thanks for replying!
