### ISSUE TITLE
Implement did:ion Recover Operation

### ISSUE THREAD

**Issue by frankhinek** [TBD54566975/web5-js#177]
## Implement support for the creation and submission of `Recover` operations for ION DIDs.

**Sidetree Spec Reference**: https://identity.foundation/sidetree/spec/#recover

**Definition of done**:
- New method(s) implemented in `DidIonMethod` class:
    - `recover()`
- New method(s) implemented in `DidManager` class:
    - `recover()`
- `DidKeyMethod` will likely need to be updated since DID Key does not have an Recover operation.  In other words, calling `didManager.update()` with a `did:key` DID should result in an error.
- Code adheres to the project's coding standards and guidelines.
- Test coverage for all new/modified code >= 90% and tests pass.
- Inline TSDoc for all added methods/utility functions.
- Code has been reviewed by at least one other [codeowner](https://github.com/TBD54566975/web5-js/blob/main/CODEOWNERS) and all comments have been addressed.
- Code has been successfully merged into the main development branch without conflicts.

**Comment by nitro-neal** [comment]
completed here https://github.com/TBD54566975/web5-kt/issues/2
