### ISSUE TITLE
Confirm 0.8 release works in TBD Docusaurus

### ISSUE THREAD

**Issue by frankhinek** [TBD54566975/web5-js#197]
### Context
Docusaurus takes an _interesting_ approach to bundling with a customized version of Webpack.  In customizing Webpack, the Docusaurus team has broken the proper interpretation of `package.json` directives.  Thus far, the only workaround has to been to add a named export to a package's `package.json` file and then explicitly import in ,the Docusaurus content page.

During the last bundler approach change a few weeks ago, extensive testing was completed for common runtimes/frameworks: https://github.com/TBD54566975/bundler-bonanza with the exception of Docusaurus.

### To Do

Complete testing with Docusaurus to verify that it can import and use `Web5.connect` from the `@web5/api` package.

**Comment by dayhaysoos** [comment]
This can be closed out after confirming that it'll work with Docusaurus after adding the browser exports again:

https://github.com/TBD54566975/web5-js/pull/192
