### ISSUE TITLE
Failed to write imported DID to store: store-managed-key  web5/api (0.8.1)

### ISSUE THREAD

**Issue by andorsk** [TBD54566975/web5-js#210]
**Expected**: I can create did using web5 api it is automatically stored in data store. 
**Actual**: It fails storing DID in store, with the following:

```sh
Error: PrivateKeyStoreDwn: Failed to write imported DID to store.
    at PrivateKeyStoreDwn.<anonymous> (file:///tmp/test-web5/node_modules/@web5/agent/dist/esm/store-managed-key.js:524:23)
    at Generator.next (<anonymous>)
    at fulfilled (file:///tmp/test-web5/node_modules/@web5/agent/dist/esm/store-managed-key.js:4:58)
```
I tested on two different machines. Node:  v18.17.1 and v18.12.1 tested.

**Reproducing:**
```
import { Web5 } from "@web5/api";

async function connect() {
  try {
    const { web5, did: myDid } = await Web5.connect();
    console.log("My DID:", myDid);
  } catch (error) {
    console.error("Error during connection:", error);
    process.exit(1); 
  }
}
connect();
```

package.json:

```json
{
  "name": "test-web5",
  "version": "1.0.0",
  "type": "module",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@web5/api": "^0.8.1"
  }
}
```

`node index.js`.

**Comment by adam4leos** [comment]
Present only on node <= 18,
 should investigate

**Comment by andorsk** [comment]
yea..seems like that was it. I think if we can improve the error message that would have been helpful. I didn't realize I was on 18, and forgot about the little imports required specifically 18. definitely my bad, but maybe there's a way to speed this up for the next person that falls into this issue ( or maybe just this ticket standing is enough )

**Comment by andorsk** [comment]
Happy to close this if we feel good about this being addressed with the imports. 

```
// node.js 18 and earlier,  needs globalThis.crypto polyfill
import { webcrypto } from "node:crypto";
// @ts-ignore
if (!globalThis.crypto) globalThis.crypto = webcrypto;
```

**Comment by adam4leos** [comment]
Funnily enough, each of the prev node v also have it's own problems, maybe should consider as well...

<img width="973" alt="Screenshot 2023-09-07 at 11 25 32 AM" src="https://github.com/TBD54566975/web5-js/assets/18248739/40e08cf4-cceb-42f9-81aa-fe00b96a0d90">

**Comment by pax-k** [comment]
I get the same error. Oddly enough the following snippet works in a NextJS API context:
```
const identity = await serverAgent.identityManager.create({
    name: 'some-agent',
    kms: 'local',
    didMethod: 'ion',
  })!;
  ```
But running the same code in a NestJS app yields: `PrivateKeyStoreDwn: Failed to write imported DID to store.`

Tested on node 18.14, 18.17, 20.8

**Comment by frankhinek** [comment]
Improvements to docs to warn when `crypto.subtle` is unavailable previously tracked here: https://github.com/TBD54566975/web5-js/issues/158
