### ISSUE TITLE
No template for issue and pull request in WEB5-js 

### ISSUE THREAD

**Issue by captain-Akshay** [TBD54566975/web5-js#235]
The repository "developer.tbd.website" contains templates for both issue creation and pull requests. It is recommended to include these templates in this repository as well. Doing so will enhance the clarity and effectiveness of contributions made by other contributors.

Fix :-
it is easy just have to make a similar template for the contributor

**Comment by captain-Akshay** [comment]
would like to work on this issue !

**Comment by Lymah123** [comment]
Can I work on this?
