### ISSUE TITLE
Support ION type index

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/web5-js#239]
https://github.com/TBD54566975/web5-js/blob/f3c7184bab45972821c89d6275eda8a6c295884f/packages/dids/src/did-ion.ts#L87

In order to support the type index we need to turn of the challenge and set the endpoint to TBD's node (https://ion.tbd.engineering/identifiers/did:ion:EiA5rVFVLghy3793kkxMTpI-gYWY-dJKO-PQGjHRNmUXNA)

**Comment by michaelneale** [comment]
is this possibly a dep of https://github.com/TBD54566975/web5-js/issues/217 ?

**Comment by decentralgabe** [comment]
It is
