### ISSUE TITLE
records.query, records.read, and records.delete fail when specifying `from` property

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/web5-js#259]
**This is using version 0.8.2-alpha-20231101-b865b10**

There's an issue when using `from` in a query: `TypeError: Cannot read properties of undefined (reading 'map')`

This works:

```js
  const response = await web5.dwn.records.query({
    message: {
      filter: {
        schema: 'https://schema.org/Playlist',
        dataFormat: 'application/json',
      },
    },
  });
```

And this (specifying `from`) fails with `TypeError: Cannot read properties of undefined (reading 'map')`:

```js
  const response = await web5.dwn.records.query({
    from: myDid,
    message: {
      filter: {
        schema: 'https://schema.org/Playlist',
        dataFormat: 'application/json',
      },
    },
  });
```

`read` also fails when `from` is specified: `TypeError: Cannot read properties of undefined (reading 'data')`

`delete` also fails when `from` is specified.

**Comment by frankhinek** [comment]
Caught up with @leordev and confirmed that he was able to resolve this by first creating the record remotely so that it could then be queried.
