### ISSUE TITLE
400 Error when calling `send()`

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/web5-js#261]
**This is using version 0.8.2-alpha-20231101-b865b10**

getting an error when calling `records.send()`  and `protocols.send()`

```js
const { record } = await web5.dwn.records.create({
    data: "this record will be written to the local DWN",
    message: {
        dataFormat: 'text/plain'
    }
});

//immediately send record to user's remote DWNs
const {status} = await record.send(userDid);
```

`userDid` is associated with the local DWN where the record was created. 

Error: `{ code: 400, detail: '/authorization: must NOT have additional properties' }`

**Comment by frankhinek** [comment]
Caught up with @leordev and confirmed that he was able to resolve this by using a `dwn-server` that was running `dwn-sdk-js` v0.2.4.
