### ISSUE TITLE
Add implementation of `did:web` to `@web5/dids`

### ISSUE THREAD

**Issue by nitro-neal** [TBD54566975/web5-js#263]
## Design Guidelines
- Support for resolution of `did:web` DIDs by `DidWebMethod` implementation.
- Test that `DidWebMethod` can be used with the existing `DidResolver` implementation.

## Feature Proposal Tasks:
- [ ] Propose API surface design prior to implementation. This can be done by creating a draft PR for a respective feature and providing prototypal code or proposing the design in the comments
- [ ] Approval Required from a minimum of 2 people

## Implementation Tasks:
- [ ] Produce/update API reference documentation for any/all methods added to the public API surface. documenting private API methods is optional
- [ ] Produce/update relevant example usage
- [ ] Test coverage must be provided for all public API methods.
- [ ] Tests that consume shared test vectors must all be passing

**Comment by TechWizard9999** [comment]
@nitro-neal
Could you please provide further details about this issue, such as specific implementation requirements and the location within the codebase where changes are expected? Your guidance on this matter would be greatly appreciated.

Thank you!

**Comment by nitro-neal** [comment]
https://github.com/TBD54566975/web5-js/pull/378
