### ISSUE TITLE
Setup artifact publishing to internal artifact registry

### ISSUE THREAD

**Issue by leordev** [TBD54566975/web5-js#289]
✅  Packages from the `web5-js` monorepo are already published to the canonical registry for JavaScript packages, [NPM Registry](https://npmjs.com).

TBD OSP is currently running a pilot to select and then deploy a repository manager for OSS projects that will centralize the storage, organization, and retrieval of software artifacts, ensuring consistent and efficient access for development and deployment processes.

Until the pilot and selection process is complete, this issue will be in TODO status with no Deadline.

**Comment by ALRubinger** [comment]
Artifactory config meeting set for Tues Jan 30

**Comment by leordev** [comment]
Done on #438
