### ISSUE TITLE
Refactor signing verifiable credentials

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/web5-js#302]
signing a verifiable credential is a bit rough around the edges at the moment - example [here](https://github.com/TBD54566975/workshop-tbdex-abc-vc-issuer/blob/main/src/api.ts#L67-L78). Specifically,

* `alg` is [hardcoded to `EdDSA`](https://github.com/TBD54566975/web5-js/blob/main/packages/credentials/src/verifiable-credential.ts#L267). This makes passing in a `signer` function as an argument unnecessary because there's only one possible DSA that can be used: `Ed25519`.
* `subjectDid` is required when calling `sign`, but also required when calling `create`. I think we can remove it as a required argument for `sign` 

@frankhinek how do you imagine `sign`'s method signature will change given the changes proposed in https://github.com/TBD54566975/web5-js/issues/271?

**Comment by frankhinek** [comment]
Thanks for the feedback @mistermoe !  Great to have someone building to reveal how the SDK can be improved.

- Agreed on the header and JWT payload details ought to be customizable.
- Yes, once we can agree on our approach to a consistent set of Key Generators, Signers, etc. that will require making changes across the DID and VC public API.

**Comment by mistermoe** [comment]
First pass of this is done. `sign` was refactored to take just a DID. will open other more focused issues as they crop up
