### ISSUE TITLE
connect() failed due to unexpected state: 2 stored identities

### ISSUE THREAD

**Issue by stevegee1** [TBD54566975/web5-js#313]
<img width="631" alt="Screenshot 2023-11-24 at 1 15 53 PM" src="https://github.com/TBD54566975/web5-js/assets/34712687/8301333d-2fde-47b1-8e5f-ead8641b356f">

```
import { Web5 } from '@web5/api';
useEffect(() => {
    const initWeb5 = async () => {
      const { web5, did } = await Web5.connect({});
   };
    initWeb5();
  }, []);
```
 I am connecting to an agent with 2 storedIdentities. Hence, the error from line **155** of [@packages/api/src/web5.ts](https://github.com/TBD54566975/web5-js/blob/main/packages/api/src/web5.ts).

 Am I  limited to one stored identity when connecting to a local agent (default) ?

**Updated test:**
My Mozilla Firefox browser returns the number of storedIdentities as 1:
<img width="1273" alt="Screenshot 2023-11-24 at 1 43 32 PM" src="https://github.com/TBD54566975/web5-js/assets/34712687/d2b6c4dd-710f-4464-8e91-a5d6687cefcf">

While, my Chrome browser returns the number of storedIdentities as 2:
<img width="467" alt="Screenshot 2023-11-24 at 1 44 52 PM" src="https://github.com/TBD54566975/web5-js/assets/34712687/b7c84178-7286-41ab-9a55-d71eaa1cfc98">

My question is, where are the storedIdentities? ...in my local storage? Can I query/delete/update the identities?
<img width="599" alt="Screenshot 2023-11-24 at 1 48 06 PM" src="https://github.com/TBD54566975/web5-js/assets/34712687/2c58db4d-38c3-40d5-8af3-e17224a77cff">

**Comment by AnuragNishad12** [comment]
are u using react.js

**Comment by AnuragNishad12** [comment]
useEffect(() => {
    const connectWeb5 = async () => {
      const { web5, did } = await Web5.connect();
      setWeb5(web5);
      setDid(did);
    };
    connectWeb5();
  }, []);
