### ISSUE TITLE
Web5.js api not integrate with next.js 

### ISSUE THREAD

**Issue by Zer-0ne** [TBD54566975/web5-js#314]
Web5.js api not integrated with next.js

code:
![image](https://github.com/TBD54566975/web5-js/assets/118300201/6d64223b-6114-4d06-88bd-ddf5ebe9834a)

error:
Error: No native build was found for platform=linux arch=x64 runtime=node abi=108 uv=1 libc=glibc node=18.13.0 webpack=true
    loaded from: /home/eagle/Documents/web5_music_app/web5_music_app./.next/server/vendor-chunks

This error happened while generating the page. Any console logs will be displayed in the terminal window.
![image](https://github.com/TBD54566975/web5-js/assets/118300201/9435535a-fdc1-45fc-b395-86348d7b7503)

plz help

**Comment by AnuragNishad12** [comment]
add next.js config file

**Comment by shamilovtim** [comment]
Hello! Please follow the [webpack configuration guide](https://developer.tbd.website/docs/web5/build/frameworks/next/#update-nextjs-webpack-configuration) and reopen if that didn't fix the issue for you.

**Comment by FrancoAguirre112** [comment]
I'm having the same problem 😪, I even tested if it was my pc, downloaded another nextjs project using web5 and it worked, checked to see if there where any different dependencies or configurations and there weren't. To clarify, I also followed the nextjs guide.

**Comment by FrancoAguirre112** [comment]
Fixed my problem by using ts instead of js for the next project, also following the nextjs node:crypto workaround after that
