### ISSUE TITLE
out of date readme ?    Web5.did.create("ion"); does not exist

### ISSUE THREAD

**Issue by fkkfrank** [TBD54566975/web5-js#317]
The main repo read me suggests   one can register an ION did right from the cals

import { Web5 } from "@web5/api";
const myDid = await Web5.did.create("ion");

Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'create')   

Web5.did  does not exist on the class.     Also not as a function of the instantiated object returned from  web5.connect() 

% npm info "@web5/api"  version      
0.8.2

https://github.com/TBD54566975/web5-js#web5didcreatemethod-options

**Comment by fkkfrank** [comment]
Maybe its possible that one must configure the DWN accept plain/text  without any protocol because in the same environment if I configure the Shared ToDo list Protocol from the tutorial the two nodes are able to send to each other.

**Comment by TechWizard9999** [comment]
@fkkfrank, I have updated the pull request with the following changes:

1. Edited the `README.md` file to provide clearer instructions for users.
2. Added step-by-step guidelines for making edits, updating content, and committing changes to the repository.
3. Included troubleshooting tips to help users address potential issues.
4. Presented alternative methods for creating Decentralized Identifiers (DIDs) to offer users more flexibility and options.

Please review the changes, and if you have any feedback, suggestions, or specific modifications in mind, please share your thoughts. Your input is valuable in ensuring that these updates align seamlessly with the project's objectives.

 look forward to hearing from you.
