### ISSUE TITLE
decouple snyk from fork prs

### ISSUE THREAD

**Issue by leordev** [TBD54566975/web5-js#319]
Fix https://github.com/TBD54566975/tbdex-js/actions/runs/6862633634/job/18660762347?pr=79#step:7:1

We probably need to use https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

**Comment by frankhinek** [comment]
Failed on this run as well:
https://github.com/TBD54566975/web5-js/actions/runs/7025497079/job/19116424727?pr=268
