### ISSUE TITLE
auto publish docs in gh pages

### ISSUE THREAD

**Issue by leordev** [TBD54566975/web5-js#333]
Use tbdocs to publish docs in gh pages (using typedoc) on new released tags/manual triggers

**Comment by TechWizard9999** [comment]
@leordev 
😊 "I'd be delighted to work on issue! Could you please assign it to me?"

**Comment by leordev** [comment]
> @leordev 😊 "I'd be delighted to work on issue! Could you please assign it to me?"

Thanks for the offer @TechWizard9999 , but this is something that I'm already working on. 😢

**Comment by ALRubinger** [comment]
Blocked on review; to re-engage

**Comment by leordev** [comment]
Completed on #402 and #408
