### ISSUE TITLE
Need API reference for web5.js - JSDoc

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/web5-js#34]
We have a high priority request for API reference docs for the web5 js sdk. Something like [this](https://tbd54566975.github.io/dwn-sdk-js/) generated by jsdoc would be sufficient.

DevRel is happy to assist if needed.

**Comment by frankhinek** [comment]
Will sync up with the team and get this queued up.

**Comment by ALRubinger** [comment]
Request by @csuwildcat - JSDoc by Tuesday, 18th April. "SGTM" - @ALRubinger @angiejones

**Comment by ALRubinger** [comment]
Moving to Phase 3 per @csuwildcat guidance on readiness.

**Comment by ALRubinger** [comment]
Assigning to @csuwildcat for triage.

**Comment by ALRubinger** [comment]
@frankhinek Could you update on whether this is available in `0.6.0`?

**Comment by frankhinek** [comment]
> We have a high priority request for API reference docs for the web5 js sdk. Something like [this](https://tbd54566975.github.io/dwn-sdk-js/) generated by jsdoc would be sufficient.
> 
> DevRel is happy to assist if needed.

@angiejones Docs now being automatically published to https://tbd54566975.github.io/web5-js/

Would be great for DevRel to assist in writing the inline docs as the coverage is very minimal at the moment.

**Comment by ALRubinger** [comment]
@frankhinek Thank you!

When you say "automatically published", is that for the latest release, or for `main`?

**Comment by frankhinek** [comment]
Identical to how it was handled with `dwn-sdk-js`: main

https://github.com/TBD54566975/dwn-sdk-js/blob/ec94bcde2d06f84ad8a2af4ea2512201a132db30/.github/workflows/document-gen.yml#L3-L6

https://github.com/TBD54566975/web5-js/blob/ee0107c7b32b9685a6665af753226b5591d83f24/.github/workflows/docs-publish.yml#L1-L8

IMHO These are very simple, temporary solutions that should be replaced with something more robust hosted on developer.tbd.website

**Comment by ALRubinger** [comment]
Thank you @frankhinek!

Agree with you - as part of some proposals we discussed around delivery/versioning norms, will draft one for OSE to review and provide input on to see if that works. For now this is phenomenal - and we need to be aware that as breaking changes enter `main`, docs will be ahead of released versions we have in Quickstart `0.6.0`, etc.

**Comment by angiejones** [comment]
> > We have a high priority request for API reference docs for the web5 js sdk. Something like [this](https://tbd54566975.github.io/dwn-sdk-js/) generated by jsdoc would be sufficient.
> > DevRel is happy to assist if needed.
> 
> @angiejones API reference now being automatically published to https://tbd54566975.github.io/web5-js/
> 
> Would be great for DevRel to assist by contributing to the inline JSDoc as the coverage is very minimal at the moment.

@frankhinek this one is pretty barren compared to the [NPM one](https://www.npmjs.com/package/@tbd54566975/web5). How is the NPM one generated?
