### ISSUE TITLE
Refactor creation and signing of verifiable presentation for web5-js

### ISSUE THREAD

**Issue by nitro-neal** [TBD54566975/web5-js#351]
Since signing has changed and we use the did's key manager instead of signOptions it is now time to bring back VerifiablePresentation

Will be similar in scope to the changes that happend recently here https://github.com/TBD54566975/web5-js/issues/302 but for VPs

**Comment by nitro-neal** [comment]
We need Verifiable Presentations to wrap our presentationSubmission. An example can be found here: https://identity.foundation/presentation-exchange/#presentation-submissions

Currently we have this (only presentationResult object, no VerifiablePresentation)
```
const presentationResult = PresentationExchange.createPresentationFromCredentials({ vcJwts: signedVcJwts, presentationDefinition: presentationDefinition })

```

I suggest we change it to be like this:
```
const vp: VerifiablePresentation = PresentationExchange.createPresentationFromCredentials({ vcJwts: signedVcJwts, presentationDefinition: presentationDefinition })
const vpJwt = await vp.sign({did:myDid})
```

The change to our existing codebase will be to: 
* Create a VerifiablePresentation model object 
* Update the createPresentationFromCredentials to construct a vp that has a presentationSubmission from the inputs it is given

**Comment by nitro-neal** [comment]
closing for duplicate: https://github.com/TBD54566975/web5-js/issues/351

**Comment by angiejones** [comment]
> closing for duplicate: [TBD54566975/web5-kt#175](https://github.com/TBD54566975/web5-kt/issues/175)

this ticket is for JS right? the "dup" is for KT

**Comment by nitro-neal** [comment]
in pr https://github.com/TBD54566975/web5-js/pull/382
