### ISSUE TITLE
Confusing to Retrieve or Generate Key Pair for DID Generation

### ISSUE THREAD

**Issue by dflbsteve** [TBD54566975/web5-js#361]
Hi,

I've been searching through the API documentation and the source code, but I'm unable to find a method to retrieve or generate the private-public key pair necessary for DID generation. Is there a specific function or section within the documentation that covers this process? Any guidance or direction would be greatly appreciated.

Cheers lot.

**Comment by frankhinek** [comment]
@dflbsteve It depends on the context of how you are working with DIDs but the DID method implementations all will generate the keys automatically, if not provided or will use the provided key set:

- [DID DHT Examples](https://github.com/TBD54566975/web5-js/blob/dbe27083b99b6d3f28d755cff882cafa14fa6630/packages/dids/tests/did-dht.spec.ts#L77-L154)
- [DID ION Examples](https://github.com/TBD54566975/web5-js/blob/dbe27083b99b6d3f28d755cff882cafa14fa6630/packages/dids/tests/did-ion.spec.ts#L99-L230)
- [DID Key Examples](https://github.com/TBD54566975/web5-js/blob/dbe27083b99b6d3f28d755cff882cafa14fa6630/packages/dids/tests/did-key.spec.ts#L10-L39)

**Comment by frankhinek** [comment]
This PR #393 will substantively change how key management works for the DID methods.  Will close this since there have been any follow up questions in the past month.  Feel free to hop on Discord or open a new issue if you've got questions with the refactored DID method implementations.
