### ISSUE TITLE
DidKeyResolver and DidIonResolver generate not used in web5

### ISSUE THREAD

**Issue by jdutchak** [TBD54566975/web5-js#38]
Curious why the DidKeyResolver and DidIonResolver generate() method was not used in web5 vs adding the ion tool again and using tweetnacl for key method? 

It seems importing creation of DIDs using the dwn-sdk-js would be a smoother implementation ??

**Comment by frankhinek** [comment]
Hey @jdutchak - Good question.  No particular reason other than it hadn't yet been addressed _yet_.

Resolved in PR #37
https://github.com/TBD54566975/web5-js/blob/786f1820986a30a81376a34d7013dfdd3e6c15c4/src/did/methods/ion.js#L2
https://github.com/TBD54566975/web5-js/blob/786f1820986a30a81376a34d7013dfdd3e6c15c4/src/did/methods/key.js#L1
