### ISSUE TITLE
Create A Results Object for all validations

### ISSUE THREAD

**Issue by nitro-neal** [TBD54566975/web5-js#386]
satisfiedPresentationDefinition to have a Results object

documentation - https://www.npmjs.com/package/@web5/credentials#satisfying-a-presentation-definition
code - https://github.com/TBD54566975/web5-js/blob/main/packages/credentials/src/presentation-exchange.ts#L45
demo test code - https://github.com/TBD54566975/web5-js/blob/main/packages/credentials/tests/presentation-exchange.spec.ts#L97

currently it is a void and only throws and error if something is wrong

This brings up a bigger point, I think we should have a generic Results object that is the same across all functions that validate, currently we have:

EvaluationResults
Validated
and this throw exception or not 

The bigger task here is to create a similar Results object for all of our validation things

**Comment by nitro-neal** [comment]
satisfiesPresentationDefinition({ vcJwts: signedVcJwts, presentationDefinition: presentationDefinition })
createPresentationFromCredentials({ vcJwts: signedVcJwts, presentationDefinition: presentationDefinition })

Yea I agree we have some funkyness here, these -almost- do the same thing

`satisfiesPresentationDefinition` - does the check to make sure the vcJwts align with the pd
`createPresentationFromCredentials` does the check to make sure the vcJwts align with the pd, and then creates the submission if valid!

so we can still have full functionality and just remove satisfiesPresentationDefinition actually, and have the result be changed to a Results object with the submission OR errors..

**Comment by nitro-neal** [comment]
List of all Verify / Validate / Satisfies functions:
```
VerifiableCredential.verify({ vcJwt: signedVcJwt }) -> void / exception
VerifiablePresentation.verify({ vpJwt: signedVpJwt }) -> void / exception

PresentationExchange.satisfiesPresentationDefinition({ vcJwts: signedVcJwts, presentationDefinition: presentationDefinition }) -> void / exception
PresentationExchange.validateDefinition({ presentationDefinition }) -> PEX Validate Object
PresentationExchange.validateSubmission({ presentationSubmission }) -> PEX Validate Object
```


and then one more that may or may not belong on this list:
```
PresentationExchange.evaluatePresentation({ presentationDefinition, presentation }) -> EvaluationResults object
```

**Comment by nitro-neal** [comment]
As far as it is possible, I want kt, js, go, rs to all have the same exact interface (as far as we can take it)
So if you can use JS you will be a pro at using KT or GO or w/e

The -original- plan was to have

try {
 // validate / verify / satisfies 
} catch (exception) {
 console.log(“NOT VALID”)
}

across every validate / verify / isValid / satisfies function

but like 2 functions kind of accidentally crept in with a Results object.

So we definitely want to make it consistent so either:
A. We use Result Objects everywhere
B. We use try / catch -> throws exception everywhere

After some discussion with users of the sdks:
**It seems like getting a result is preferred:**

Reasons:
* People were confused in the JS when they didn't get a result back from those methods
* Based on the name, it just screamed to me that something would be returned 
* I would like a result as well... even if it's a true when no data is returned and an exception when it fails. I think that could help us with consistency?
* Result objects it just feels clearer

Based on this feedback I'll come up with a proposal to
* Rename things so like it makes more sense (maybe everything has validate in the name or something)
* Come up with a results object that works in all languages and verify / validate functions

Some **very early** thoughts on the Results object:

```
class ValidationResult(
    val isValid: Boolean,
    val errors: List<String>,
    val warnings: List<String>
)
```

**Comment by nitro-neal** [comment]
in doing experimentation I think this is all we need:
```
export class ValidationResult {
  constructor(public success: boolean, public message: string = '',) {}
}
```

**Comment by nitro-neal** [comment]
And these would be the functions to use it:

```
  await VerifiableCredential.verify({ vcJwt: signedVcJwt })
  await VerifiablePresentation.verify({ vcJwt: signedVcJwt })
  PresentationExchange.satisfiesPresentationDefinition({ vcJwts: signedVcJwts, presentationDefinition: presentationDefinition })
  PresentationExchange.validateDefinition({ presentationDefinition })
  PresentationExchange.validateSubmission({ presentationSubmission })
```

**Comment by nitro-neal** [comment]
Overall Proposed Changes:

Shared validation result object
```
export class ValidationResult {
  constructor(public success: boolean, public message: string = '',) {}
}
```


Usage on functions that verify / validate
```
const result: ValidationResult  = await VerifiableCredential.verify({ vcJwt: signedVcJwt })
const result: ValidationResult  = await VerifiablePresentation.verify({ vcJwt: signedVcJwt })

const result: ValidationResult  = PresentationExchange.satisfiesPresentationDefinition({ vcJwts: signedVcJwts, presentationDefinition: presentationDefinition })

const result: ValidationResult  = PresentationExchange.validateDefinition({ presentationDefinition })
const result: ValidationResult  = PresentationExchange.validateSubmission({ presentationSubmission })
```

Renaming of a function:
```
const evaluationResults = PresentationExchange.evaluatePresentation({ presentationDefinition, presentation })
```


To this:
```
type WithPresentationDefinition = {
  vcJwts: string[];
  presentationDefinition: PresentationDefinitionV2;
};

type WithPresentationSubmission = {
  vcJwts: string[];
  presentationSubmission: PresentationSubmission;
};

type SatisfiesPresentationOptions = WithPresentationDefinition | WithPresentationSubmission;

const result: ValidationResult  = PresentationExchange.satisfiesPresentationDefinition({ options: SatisfiesPresentationOptions })
```

So the final api surface will be:

```
// functions that use ValidationResult
const result: ValidationResult  = await VerifiableCredential.verify({ vcJwt: signedVcJwt })
const result: ValidationResult  = await VerifiablePresentation.verify({ vcJwt: signedVcJwt })

const result: ValidationResult  = PresentationExchange.validateDefinition({ presentationDefinition })
const result: ValidationResult  = PresentationExchange.validateSubmission({ presentationSubmission })

const result: ValidationResult  = PresentationExchange.satisfiesPresentationDefinition({ options: SatisfiesPresentationOptions })

// functions that return an object OR throw an exception
const vc = await VerifiableCredential.create({ ... });
const vcJwt = await vc.sign({ did: issuer });

const vp = await VerifiablePresentation.create({ ... });
const vpJwt = await vp.sign({ did: issuer });

const vc = VerifiableCredential.parseJwt({ vcJwt: signedVcJwt })
const vp = VerifiablePresentation.parseJwt({ vpJwt: signedVpJwt })

const selectedCredentials = PresentationExchange.selectCredentials({ ... })
const presentationResult = PresentationExchange.createPresentationFromCredentials({ ... })
```

**Comment by nitro-neal** [comment]
open question:
```
const result: ValidationResult  = await VerifiableCredential.verify({ vcJwt: signedVcJwt })
```

Would it be possible for this to EVER throw an exception? Or should we catch every exception that could happen

**Comment by nitro-neal** [comment]
Full PEX flow for reference:

```js
// Portable Dids
issuerDid = await DidKeyMethod.create();
subjectDid = await DidKeyMethod.create();

const vc = await VerifiableCredential.create({
  type    : 'StreetCred',
  issuer  : issuerDid.did,
  subject : subjectDid.did,
  data    : new StreetCredibility('high', true),
});

const vcJwt = await vc.sign({ issuerDid });

const presentationSubmission = PresentationExchange.createPresentationFromCredentials({
  vcJwts: [vcJwt],
  presentationDefinition
});

const vp = await VerifiablePresentation.create({
  holder         : holderDid.did,
  vcJwts         : [validVcJwt],
  additionalData : {
    presentation_submission: presentationSubmission
  },
  type: 'PresentationSubmission'
});

const vpJwt = await vp.sign({ issuerDid });
```

**Comment by decentralgabe** [comment]
I like the approach and broadly think we need to consider the different levels of validation and verification we expose. It should look something like this:

**For a VC**
1. Is the signature valid (verification)?
2. Is the VC compliant with the data model?
3. Is it expired?
4. Is the data valid against its given json schemas?
5. Is the issuer expected (trusted, known, trusted for this kind of cred?)
6. Is the status valid (e.g. not revoked, suspended - or do we WANT one of these statuses?)
7. Other concerns, like business logic validation (e.g. evidence makes sense, subject data is pertinent)

**For a VP**
1. Is the signature on the VP valid?
2. Is the signer of the VP authorized to present the VC(s) in the presentation?
3. Is it expired?
4. Is the data valid against its given json schemas?
5. For each VC in the VP, the concerns listed above

Similar for Preesntation Exchange scenarios.

**Comment by nitro-neal** [comment]
In a meeting between us we came out with the following action items:

* Split out Verifys into multiple Verifies that do different things OR have a verify options
* Get real world usage data from PFI exemplar
* Leave the Verifies / Validates as is for now
* Update evaluatePresentation to share satisfiesPresentationDefinition function overload
* Change everything to be a throws for now (like kotlin)

```
eg:
vc.verify()
* Is the signature valid (verification)?
* Is it expired?

vc.verifyDataModel()
* Is the data valid against its given json schemas?
* Is the VC compliant with the data model?
```

**Comment by nitro-neal** [comment]
verifyIntegrity - jwt integrity check
verifySignature - cryptographic verification
verifyVcDataModel - verifies if it is a valid vc data model
verifyExpiration - makes sure it is not expired
verifyStatus - sees if the status list credential exists and if it is valid

**Comment by decentralgabe** [comment]
@nitro-neal verifySchema?

**Comment by nitro-neal** [comment]
All findings have been documented here https://hackmd.io/gSpcRv7dTe21Qap2XB5D0g?view and all issues have been created
