### ISSUE TITLE
Cut new release for Bitcoin++

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/web5-js#42]
@csuwildcat's raised that a new Web5 release will be the basis for workshops and presos around Bitcoin++. The Developer Site docs and Quickstart will be updated to this release. OSE to provide:

* Version number (ie. `0.4.0`, to be used in docs e.g. `@tbd54566975/web5@0.4.0`)
* CDN Location (ie. `https://cdn.jsdelivr.net/npm/@tbd54566975/web5@0.4.0/dist/browser.mjs`)

**Comment by frankhinek** [comment]
Release cut: [v0.6.0](https://github.com/TBD54566975/web5-js/releases/tag/v0.6.0)

and auto published to NPM: https://www.npmjs.com/package/@tbd54566975/web5/v/0.6.0

**Comment by ALRubinger** [comment]
Thank you @frankhinek!
