### ISSUE TITLE
`PresentationExchange.selectCredentials` returns all vcJwts when none match

### ISSUE THREAD

**Issue by kirahsapong** [TBD54566975/web5-js#447]
Given an array of JWTs where NONE of the credentials satisfy the given PD, ALL credentials are returned from `PresentationExchange.selectCredentials()`. This only happens when NONE of the credentials match. If there's at least one credential that satisfies the PD, then `selectCredentials()` works.

**Steps to reproduce**
1. Create a `presentationDefinition` with input descriptors
2. Create an array of `vcJwts` where none of the `vcJwts` satisfies the `presentationDefinition`
3. Call `PresentationExchange.selectCredentials(vcJwts, presentationDefinition)`

**Current behaviour**
Return value will be the original array of vcJwts

**Expected behaviour**
Return value should be an array with a size of 0

_**Sidenote (if you have time)**_: `satisfiesPresentationDefinition` should return a boolean instead of throwing when vcJwts do not satisfy. Throwing causes code to stop executing which doesn't work for iterating over a list to filter out presentation definitions

**Comment by nitro-neal** [comment]
pr here - https://github.com/TBD54566975/web5-js/pull/450
