### ISSUE TITLE
Error:    looks like `alg` param missing from create did in keyPair?

### ISSUE THREAD

**Issue by jdutchak** [TBD54566975/web5-js#50]
for did:key:...

ERROR: "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'alg')
    at Xa.createSignatureInput (jws.ts:90:46)
 '
 `
"keyPair": {
        "publicKeyJwk": {
alg ????
          "crv": "Ed25519",
          "kid": "z6MkueXPZmxkPSApkJFnjbAok4W17hjMUvR5NaG425dDUJHd",
          "kty": "OKP",
          "x": "4cIK8delERqe57cDndw4Nlrg4ZzZcBbfu8TxpKghpSA"
        },
        "privateKeyJwk": {
alg ????
          "crv": "Ed25519",
          "kid": "z6MkueXPZmxkPSApkJFnjbAok4W17hjMUvR5NaG425dDUJHd",
          "kty": "OKP",
          "x": "4cIK8delERqe57cDndw4Nlrg4ZzZcBbfu8TxpKghpSA",
          "d": "pp8yaIqoOXJKTNNJHLWiV7HRbFV8rC4vB40X6Bczdjfhwgrx16URGp7ntwOd3Dg2WuDhnNlwFt-7xPGkqCGlIA"
        }
`

**Comment by Voronar** [comment]
`Yup you got it, only ion works inside of the web5 did create, otherwise you can 'bring your own key' with any other lib and make a did key` from TBD Discord channel by TBD-Neal.

**Comment by michaelneale** [comment]
@jdutchak can you describe how you got that? (2 releases since then I think).
