### ISSUE TITLE
[api] Unexpected error: Expected 1 but found 2 stored identities. When calling `Web5.connect()`

### ISSUE THREAD

**Issue by LiranCohen** [TBD54566975/web5-js#680]
When using `Web5.connect()` without any options, there have been occurrences where the following error is thrown:
`Uncaught (in promise) Error: connect() failed due to unexpected state: Expected 1 but found 2 stored identities.`

When `connect()` is called and no identities are returned from the agent, a new identity is created.
There is some unknown scenario where `userAgent.identities.list()` is returning zero results, although there was one that existed in the past.

On a subsequent call of `connect()` it will then suddenly have 2 identities.
https://github.com/TBD54566975/web5-js/blob/main/packages/api/src/web5.ts#L205-L248

For the time being we will do a few things to remedy the stuck situation, as well as investigate further as to why this happens.
1. Check the status returned by `processRequest` within the `DwnDidStore.getAllRecords()` and throw an error along with the error detail if it does not return a 200 status. https://github.com/TBD54566975/web5-js/blob/main/packages/agent/src/store-did.ts#L48-L57
2. If the user passes a `connectedDid` and the list returns more than one identity, attempt to find the identity which matches the `connectedDid`, if it exists use that identity, otherwise fail.

**Comment by csuwildcat** [comment]
Hopefully connectedDid is the DID identifier, not some more complex thing?

**Comment by LiranCohen** [comment]
> Hopefully connectedDid is the DID identifier, not some more complex thing?

Yup! It is set to the `identity.did.uri` further down the file if there is no agent passed.

**Comment by LiranCohen** [comment]
This was partially done during the connect flow.

Currently if multiple identities exist, the first in the index is returned. Closing in favor of better-defined behavior for multi-DID management.
