### ISSUE TITLE
CORS issue on Web5.connect()

### ISSUE THREAD

**Issue by LiranCohen** [TBD54566975/web5-js#80]
When I try to initialize a DWN/DID through Web5.connect() on a frontend application running locally, I am met with a CORS error response from https://dwn.tbddev.org/.well-known/did.json

```
const { did } = await Web5.connect();
```

```Access to fetch at 'https://dwn.tbddev.org/.well-known/did.json' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.```

```GET https://dwn.tbddev.org/.well-known/did.json net::ERR_FAILED 200```

**Comment by michaelneale** [comment]
Ah. The default server doesn’t have cors as is fronted with nginx. will look at correcting it (if connecting directly to a DWN then I think preflight check works)

**Comment by michaelneale** [comment]
@LiranCohen lets see how badly I can break nginx...

**Comment by michaelneale** [comment]
@LiranCohen fixed now - please try again

**Comment by mistermoe** [comment]
@LiranCohen thanks for flagging!

**Comment by LiranCohen** [comment]
Works as expected now!
