### ISSUE TITLE
Protocols are required to send to another did?

### ISSUE THREAD

**Issue by michaelneale** [TBD54566975/web5-js#83]
{code: 401, detail: 'message failed authorization, permission grant check not yet implemented'}

if I try to send from client1 to client2, I get this error message above. I assume that is client2 knows nothing about me? and I need to have a protocol to allow client1 to receive it?

**Comment by csuwildcat** [comment]
Without permissions implemented, yes, our only means of allowing external parties to write to your DWeb Node is by having a protocol present that opens up access to 'allow anyone to write X', whatever X is specified to be in said protocol.
