### ISSUE TITLE
Make hosted DWNs and sync configurable

### ISSUE THREAD

**Issue by frankhinek** [TBD54566975/web5-js#86]
Making the hosted DWNs  was a planned fast-follow to the 0.7.x release, but adding an issue to track since it was requested by multiple community members (example below).

<img width="739" alt="Screenshot 2023-05-22 at 1 19 10 PM" src="https://github.com/TBD54566975/web5-js/assets/134693/10c9cef9-cd3f-489b-9c59-2228f8d51634">

**Comment by michaelneale** [comment]
I am taking a look at this.

**Comment by michaelneale** [comment]
`const { web5, did: myDid } = await connect({ 'dwnEndpoints': ['https://dwn.tbddev.org/dwn0'] });`

**Comment by frankhinek** [comment]
Modifying this issue to only concern making hosted DWNs configurable.  New issue #95 created to track allowing sync behavior to be configurable.
