### ISSUE TITLE
Mobile Browsers

### ISSUE THREAD

**Issue by demattosanthony** [TBD54566975/web5-js#90]
Not able to use web.connect() on a mobile browser. Not sure if this is an issue on my part of the package.

The code:

```
try {
    const { web5, did: myDid } = await Web5.connect();
    
      setUserDetails({ did: myDid });
} catch (err) {
    console.error(err);
}
```

The error I see on the mobile browser.

![IMG_2587](https://github.com/TBD54566975/web5-js/assets/70538060/54ac052b-d478-4972-a98f-1d2c547374e3)

**Comment by frankhinek** [comment]
Thanks for submitting the Issue.

I suspect that the issue isn't mobile browser related and that the same error would be reported if you tried to access http://192.168.3.105:4000 from a desktop browser.

The error originates from [`crypto.subtle`](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto) not being permitted by browsers outside of "secure contexts"

<img width="794" alt="Screenshot 2023-05-23 at 5 15 17 PM" src="https://github.com/TBD54566975/web5-js/assets/134693/c0d6e6a9-6a9f-42ea-8512-337c731008e5">

I shared some links below if you are curious about the full details, but the TL;dr is that the most commonly encountered "secure contexts" are:

- HTTPS
- http://localhost/
- http://localhost:port/

This is why it works when you're on the device hosting the HTTP server accessed via http://localhost:4000/ but not from a mobile device using http://192.168.3.105:4000/.  `http` that is _not_ `localhost` is not a "secure context" so the browser won't let you access the Web Crypto API.

Potential solutions include enabling HTTPS on your Next.js web server (e.g., Let's Encrypt certs) or using local PWAs (progressive web apps) on your mobile.

We'll keep the issue open for a couple of days in case you have follow-up questions or feel free to follow-up on Discord.

References:
- https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts
- https://w3c.github.io/webappsec-secure-contexts/
